# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=20)),
                ('password', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
