# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 15:13
from __future__ import unicode_literals

import SocialNetworking.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SocialNetworking', '0002_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=300)),
                ('datecommented', models.DateField(auto_now_add=True)),
                ('timecommented', models.TimeField(auto_now_add=True)),
                ('user', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Newsfeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(default='', max_length=300)),
                ('postmodified', models.CharField(default='', max_length=300)),
                ('datepublished', models.DateField(auto_now_add=True)),
                ('timepublished', models.TimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, height_field='heightimg', null=True, upload_to=SocialNetworking.models.image_upload, verbose_name=SocialNetworking.models.image_upload, width_field='widthimg')),
                ('heightimg', models.IntegerField(default=0)),
                ('widthimg', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstn', models.CharField(default='', max_length=50)),
                ('lastn', models.CharField(default='', max_length=50)),
                ('email_id', models.EmailField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=10)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=50)),
                ('birthdate', models.DateField(default=datetime.date(2017, 9, 20))),
                ('gender', models.CharField(default='', max_length=50)),
                ('languages', models.CharField(default='', max_length=50)),
                ('display', models.ImageField(default='/user_profile/images.png', null=True, upload_to=SocialNetworking.models.image_upload_user)),
            ],
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='containern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialNetworking.Signup'),
        ),
        migrations.AddField(
            model_name='comments',
            name='containerc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialNetworking.Newsfeed'),
        ),
    ]
