# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetworking', '0003_auto_20170920_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='timecommented',
        ),
        migrations.RemoveField(
            model_name='newsfeed',
            name='timepublished',
        ),
        migrations.AlterField(
            model_name='comments',
            name='datecommented',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='datepublished',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
