# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 18:49
from __future__ import unicode_literals

import SocialNetworking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetworking', '0005_auto_20170920_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='display',
            field=models.ImageField(null=True, upload_to=SocialNetworking.models.image_upload_user),
        ),
    ]
