# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 21:22
from __future__ import unicode_literals

import SocialNetworking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetworking', '0006_auto_20170920_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='lastloggedin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='display',
            field=models.ImageField(default='/user_profile/images.png', null=True, upload_to=SocialNetworking.models.image_upload_user),
        ),
    ]
