# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetworking', '0007_auto_20170920_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='lastloggedin',
            field=models.DateTimeField(),
        ),
    ]
