# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetworking', '0014_auto_20170921_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
