# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetworking', '0015_signup_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_name', models.CharField(default='', max_length=50)),
                ('super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialNetworking.Signup')),
            ],
        ),
    ]
