# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetworking', '0019_auto_20170921_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='containerc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialNetworking.Newsfeed'),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='containern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialNetworking.Signup'),
        ),
    ]
