# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetworking', '0020_auto_20170921_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='datecommented',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='datepublished',
            field=models.CharField(default='', max_length=20),
        ),
    ]
