# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetworking', '0021_auto_20170921_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='datecomchar',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='datepubchar',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='comments',
            name='datecommented',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='datepublished',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
